spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    passward: 123456
    url: jdbc:mysql://192.168.5.16/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
